### ISSUE TITLE
Updates for the Cannabis Village

### ISSUE THREAD

**Issue by montagist** [BeezleLabs/hackertracker.github.io#1]
Made some changes to the ordering and times in the schedule.

Also made a new column in the spreadsheet (Desc.) with hash links that go to the full description for each speaker/talk. Could you please have the person doing the update use those for the descriptions in hackertracker? They were just using the much shorter "notes" from the spreadsheet before (and I get why, I probably hadn't made that clear). That link and some minor changes ive made to the site should make it far easier to just copy paste. LMK if I can do anything else to help facilitate :) 

just to refresh your memory, spreadsheet's at https://bit.ly/puffpuffhack_sched

**Comment by sethlaw** [comment]
thanks, no longer needed as an issue.
