### ISSUE TITLE
Adding ShellCon 2019

### ISSUE THREAD

**Issue by daschu117** [BeezleLabs/hackertracker.github.io#5]
Hi! ShellCon is next week and we'd love to get our conference into the app. What's the best way to go about doing that? 

Do the IDs need to be globally unique across all of the cons? What is a safe range that we can use? 

Do the IDs need to unique between the different files? As in, do the events and the speaker IDs need to be from different ranges?

Thanks!

**Comment by sethlaw** [comment]
Hey @daschu117, we need the format that's in each of the different folders here. Ata a minimum, send us over event_types.json, locations.json, speakers.json and events.json. I have some scripts to import in all the data in a proper format and not collide with other IDs/conferences. Email me at seth.w.law [at] gmail.com to talk more.
